### PR TITLE
Upgraded Ruby to 2.3.0 and Rails to 4.2.5; Added simple .travis.yml file

### PR DESCRIPTION
**Pull request by jasnow**
* Upgraded Ruby to 2.3.0.
 * Upgraded Rails to 4.2.5.
 * Add simple .travis.yml file. Yes, TODO: need to add .env stuff too.

### CODE REVIEW

**Comment by jasnow** [comment]
Now I see that you use CircleCI.

**Comment by jasnow** [comment]
Suggest that I will delete above .travis.yml in next PR and add it to .gitignore file.

**Comment by schneidmaster** [comment]
Yeah sounds good, if you remove the travis.yml and push to this PR I will merge, thanks

**Comment by jasnow** [comment]
@schneidmaster - removed travis.yml as requested.

**Pull request merged**
