### PR TITLE
indexes reports on precinct and aasm state

### PR DESCRIPTION
**Pull request by gnarf**
This should result in faster csv generations and fewer heroku timeouts.

worked with @lady3bean on this one

### CODE REVIEW

**Comment by schneidmaster** [comment]
I don't think an index is the right solution -- there are only a few thousand rows in the reports table; the where clause isn't causing the slowness. It's because there's an n+1 query since the precinct of each report is referenced in the CSV generation requiring a "select * from precincts where id = ?" for each row. I'm adding some eager loading (aka sql join in Rails) to fix that issue.

**Comment by schneidmaster** [comment]
(Incidentally, your PR didn't break the tests, I haven't updated them for the last-minute changes I made for NV.)

**Comment by gnarf** [comment]
yup - i agree after seeing that...

silly ruby...

**Comment by schneidmaster** [comment]
Now now, we will not tolerate slander of ruby's good name in this repository :wink:

Closing PR, will fix the n+1 separately tomorrow.

**Comment by gnarf** [comment]
Well, the fact that upon cursory inspection, I didn't notice that second query being needed makes it pretty silly...

**Comment by gnarf** [comment]
Don't you already have all the needed precint data in the function outside anyway?

https://github.com/gnarf/CaucusCentralAPI/blob/28174096e553ccc3bf86a7a93f05936383e41d6b/app/controllers/api/v1/states_controller.rb#L29

Couldn't you just pass that `current_state.precincts` into your `to_csv` and reference it via the ID?

**Comment by schneidmaster** [comment]
That's only the precinct IDs, not the whole precinct models (because of the `pluck(:id)` on the end). It's equivalent to `select id from precincts...` which is more performant. I could load all of the precincts there and pass them into the function but there's no reason that's better than just doing a proper join on the reports query.

**Comment by gnarf** [comment]
sure -- sorry I couldn't fend my way through the rails magic here, ruby not
very familiar to me... thanks for the quick education on it :)

**Comment by lady3bean** [comment]
Even if it's not the root cause, the indexing should still speed this up, esp. if the data grows as more states are added.

**Comment by schneidmaster** [comment]
Indices don't cause any noticeable speedup until you hit probably 100k rows and even then we're talking fractions of a second off a query executed once per request -- even if we use this on all caucus states at Iowa/Nevada scale we aren't going to pass 30k.

**Comment by gnarf** [comment]
Also true... These indexes are probably still valuable as they would be
main where clauses in almost any query of this table right?

**Comment by schneidmaster** [comment]
I mean it's not like indices hurt anything, I'm just saying they won't cause any noticeable speedup for our use case.

**Comment by gnarf** [comment]
Fair, might as well land a contribution then?

**Comment by schneidmaster** [comment]
Yeah sure. If we're going this route, though, would you mind adding indices to the other places they'd help out? E.g. the fields we search on in the user/precinct tables.

**Comment by gnarf** [comment]
Happy to take another pass and do that yeah!

Won't get to it until later tonight at the earliest though.

**Comment by schneidmaster** [comment]
Yeah no worries! Thanks.

**Pull request closed without merging**
